version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-dashboard-dht11
    ports:
      - "8050:8050"
    environment:
      - PORT=8050
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - iot-network
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    stdin_open: true
    tty: true

networks:
  iot-network:
    driver: bridge
